### PR TITLE
process_data()

### PR DESCRIPTION
**Pull request by DFrostByte**
- Removed unnecessary code that tests for escaped characters.
- Simplified dynamic string allocation by using strndup.
- Improved name and value extraction by catering for missing values.
- Generally refactored resulting in better readability.
- Substituted use of malloc for calloc so as not to have to use memset().
- Memory allocation now only occurs if a 'name' is found. This is more robust as it handles "dodgy" urls / data.

### CODE REVIEW

**Comment by DFrostByte** [comment]
Against the current master branch, the following code fails at assertion 5. I don' t believe these
"equivalent" malformed query strings should result in different data sets.

```c
static void
test_process_data(void)
{
	formvars *fvp, *iter;
	const char *data[] = {"1=one&second=%20.two-%30&33=three+three",
	                      "&1=one&second=%20.two-%30&33=three+three",
	                      "=noname&1=one&&second=%20.two-%30&33=three+three",
	                      "==&&=&&1=one&second=%20.two-%30&==&33=three+three&=&",
	                      NULL};
	int i;

	for (i = 0; data[i]; ++i)
	{
		assert(formvars_start == NULL);
		assert(formvars_last == NULL);

		fvp = process_data(data[i], &formvars_start, &formvars_last, '=', '&');

		assert(formvars_start && formvars_last && fvp);
		assert(fvp == formvars_start);

		assert(! strcmp(fvp->name, "1"));
		assert(! strcmp(fvp->value, "one"));
		assert(iter = fvp->next);

		assert(! strcmp(iter->name, "second"));
		assert(! strcmp(iter->value, " .two-0"));
		assert(iter = iter->next);

		assert(! strcmp(iter->name, "33"));
		assert(! strcmp(iter->value, "three three"));

		assert(iter == formvars_last);
		assert(! (iter = iter->next));

		cgi_end();
	}
}
```

**Comment by LeSpocky** [comment]
Damn, I mixed up the commit message for the merge commit with a comment here. So here again:

Reviewed these commits. For the future and according to git best practices: could you please use the first line of a commit message to summarize what this commit is about in 50 to 70 chars, leave a blank line and add the more detailed description then? See e.g. [Git Commit Messages : 50/72 Formatting](https://stackoverflow.com/questions/2290016/git-commit-messages-50-72-formatting). This makes review easier.

Regarding the failed tests: I suggest creating an [issue](https://github.com/rafaelsteil/libcgi/issues) if your opinion is this is an error. I didn't think about it yet what is allowed and how libcgi should handle malformed input data.

**Comment by LeSpocky** [comment]
Another thing: you used rawmemchr() which seems to be a GNU extension of the libc, which maybe makes this less portable. For now this is okay I guess. I don't have much experience with such portability issues nor do I have non GNU machines for building and testing. Maybe we fix such problems, if somebody actually needs it.

**Comment by DFrostByte** [comment]
RE: failed tests
I don't regard this as an error, per se, just that it makes sense to filter out "garbage" instead of holding on to it. Particularly as it's so simply incorporated into the algorithm. Also, it's partly helping efficiency by not allocating memory for data that would never be wanted.

RE: rawmemchr()
I share your opinion. Two easy fixes should we desire to do so:
1. Substitute with strchr()
2. Use a macro to substitute strchr() if rawmemchr isn't available.

**Pull request merged**
