### PR TITLE
cgi_param_multiple()

### PR DESCRIPTION
**Pull request by DFrostByte**
Improved cgi_param_multiple() by caching link iterator so as not to begin search from formvars_start each time the function is called.

modified:   cgi.c

### CODE REVIEW

**Comment by LeSpocky** [comment]
You're right, the static variable is problematic. In this case I merge it, because there was a static variable before. Removing this would probably require rewriting huge parts of the library?

**Comment by DFrostByte** [comment]
Actually, as it's only a user function that no other library functions depend on, there wouldn't be a need to rewrite anything else. It would, of course, change the library's interface for this function.

Sticking with the static variable, I would consider adding another to cache the search criteria. This would allow searching for a new criteria before returning all occurrences of the previous. Currently, if this is attempted, any list items previously iterated would be skipped. Of course, this wouldn't help in a situation where the function could be called back and forth between 2 or more criteria; only the re-entrant changes suggested would accommodate that.

**Comment by LeSpocky** [comment]
For the moment I'd like to keep the API as close to the v1.0 as possible. What do you think about collecting ideas and suggestions for a new API version in a wiki page?

**Comment by DFrostByte** [comment]
Makes sense to me.

**Comment by LeSpocky** [comment]
Well then: [New API](https://github.com/rafaelsteil/libcgi/wiki/New-API)

**Pull request merged**
